module.exports = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_NOT_COMPLETED: 'SHOW_NOT_COMPLETED',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}